### ISSUE TITLE
急需翻页功能，以及快捷键功能

### ISSUE THREAD

**Issue by AliangYsl** [nancheung/legado-reader#12]
现在滚动看书，滚动一下，都不知已经刚到哪里了，很烦

**Comment by nancheung** [comment]
dpi这么高么，快捷键有计划做了。
目前主要在完善“在代码行内阅读”的功能：https://github.com/nancheung/legado-reader/releases/tag/v1.2-SNAPSHOT
如果这个特性上线我觉得你可以用这个功能哈哈

**Comment by nancheung** [comment]
你给我提醒了，这个功能我可以支持一次性显示多行的

**Comment by nancheung** [comment]
你觉得需要哪些快捷键呀，我现在实现了上下章的快捷键

**Comment by AliangYsl** [comment]
> 你觉得需要哪些快捷键呀，我现在实现了上下章的快捷键

上下翻页，很重要，如果没有这个，纯靠鼠标滚动的话，手离不开鼠标（不像个程序猿），程序猿应该是不离开键盘，码几行代码，然后翻一页这样

**Comment by nancheung** [comment]
> > 你觉得需要哪些快捷键呀，我现在实现了上下章的快捷键
> 
> 上下翻页，很重要，如果没有这个，纯靠鼠标滚动的话，手离不开鼠标（不像个程序猿），程序猿应该是不离开键盘，码几行代码，然后翻一页这样

ok，目前你可以把鼠标点到正文内容中间，上下移动有类似效果

**Comment by nancheung** [comment]
最新版进入正文页后，默认会将光标焦点置于文本框中。
翻页可利用上下方向键，或者PageUp/PageDown（翻页键）；
上下章可使用默认的Alt+Shift+左/右方向键，或者自己在按键映射自定义设置中搜索”Legado Reader“自定义快捷键
