### ISSUE TITLE
图标太大

### ISSUE THREAD

**Issue by cqwuzonglin** [nancheung/legado-reader#13]
这么大的图标 放不下啊
![image](https://user-images.githubusercontent.com/45115566/221730022-04f7188f-dd71-49bc-9a31-8542fea139a2.png)

**Comment by nancheung** [comment]
这个bug已修复，没发版。是在非暗黑模式下会出现这个问题。我稍后发个修复版本吧

**Comment by nancheung** [comment]
https://github.com/nancheung/legado-reader/releases/download/v1.1.1/legado-reader-1.1.1.zip
