### ISSUE TITLE
BUG:插件会变得越来越宽

### ISSUE THREAD

**Issue by berial** [nancheung/legado-reader#14]
随着切换章节，放在右侧的插件会变得越来越宽。

**Comment by nancheung** [comment]
初步猜测是被顶部的章节名给顶开了。
有些章节名比较长，把插件顶宽之后，就不会缩回去了

**Comment by berial** [comment]
然后滚动条也会消失，必须得把插件拉到更宽

**Comment by nancheung** [comment]
> 然后滚动条也会消失，必须得把插件拉到更宽

对，这个我使用下来也有发现，因为整个插件都变宽了。。这个属于页面大小自适应的问题，因为插件界面无法缩到很小，被按钮等组件给顶住了。这块有打算大改，让后续插件可以缩放到极小

**Comment by berial** [comment]
好吧，大佬加油

**Comment by nancheung** [comment]
> 好吧，大佬加油

都是为了让写代码更轻松~

**Comment by nancheung** [comment]
最新版已修复
