### ISSUE TITLE
似乎不会向reader服务端发送阅读进度

### ISSUE THREAD

**Issue by smokeriu** [nancheung/legado-reader#15]
能够获取reader服务器端的阅读进度，但通过该插件阅读的进度似乎不会同步回服务器。

另外我暂时不知道在哪看该插件的log，所以无法反馈更多内容。

- IDEA版本: IntelliJ IDEA 2023.1 (Ultimate Edition)
- 插件版本: 1.4
- 网络环境: 通过zerotier穿透回家里的服务器。

**Comment by nancheung** [comment]
help->about->show log in explorer，打开idea.log，搜索“saveBookProgress”

**Comment by nancheung** [comment]
刚刚我使用官方的试用版：https://reader.htmake.com，可以正常同步章节。
你服务器版本是啥，是不是服务器版本太老的问题

**Comment by nancheung** [comment]
超过1月未回复，关闭此issues
