### ISSUE TITLE
可不可以自定义字体大小

### ISSUE THREAD

**Issue by Meng-X-G** [nancheung/legado-reader#18]
默认的0还是感觉好小
还有可以自定义字体吗

**Comment by nancheung** [comment]
0代表默认，实际上是你当前IDE设置的字体大小，字体大小是可以设置的，字体目前还不支持自定义，如果确实需求较大，可以考虑加上

**Comment by Meng-X-G** [comment]
好的，感谢

**Comment by Meng-X-G** [comment]
设置完合适的大小后，IDE的字体大小就很难看了，希望还是有个单独设置字体的功能

**Comment by Meng-X-G** [comment]
好吧，是我傻了，我以为数字越大字体越小，一直设置的0以为最大了。感谢！
